<?PHP
function InsertTimeCard($con, $dataId, $newformat, $JamMasukAsli){
	$vID = 0;
	$queryID = "SELECT B.PERSON_ID
	, D.ORGANIZATION_ID
	, D.LOCATION_ID
	, HL.LOCATION_CODE
	, B.FULL_NAME
	, CASE MMUS.SPV_ID WHEN 0 THEN '' 
	ELSE (SELECT PPFS.FULL_NAME FROM APPS.PER_PEOPLE_F PPFS WHERE PPFS.PERSON_ID=MMUS.SPV_ID AND PPFS.EFFECTIVE_END_DATE > SYSDATE) END AS SPV
	, CASE MMUS.SPV_ID WHEN 0 THEN '' 
	ELSE (SELECT PPFS.EMAIL_ADDRESS FROM APPS.PER_PEOPLE_F PPFS WHERE PPFS.PERSON_ID=MMUS.SPV_ID AND PPFS.EFFECTIVE_END_DATE > SYSDATE) END AS EMAIL_SPV
	, CASE MMUS.MANAGER_ID WHEN 0 THEN '' 
	ELSE (SELECT PPFM.FULL_NAME FROM APPS.PER_PEOPLE_F PPFM WHERE PPFM.PERSON_ID=MMUS.MANAGER_ID AND PPFM.EFFECTIVE_END_DATE > SYSDATE) END AS MANAGER 
	, CASE MMUS.MANAGER_ID WHEN 0 THEN '' 
	ELSE (SELECT PPFM.EMAIL_ADDRESS FROM APPS.PER_PEOPLE_F PPFM WHERE PPFM.PERSON_ID=MMUS.MANAGER_ID AND PPFM.EFFECTIVE_END_DATE > SYSDATE) END AS EMAIL_MANAGER 
	FROM APPS.PER_PEOPLE_F B 
	INNER JOIN APPS.PER_ASSIGNMENTS_F D ON B.PERSON_ID = D.PERSON_ID
	INNER JOIN APPS.HR_LOCATIONS HL ON HL.LOCATION_ID=D.LOCATION_ID
	LEFT JOIN MJ.MJ_M_USERAPPROVAL_SPLBETON MMUS ON MMUS.PLANT_ID=D.LOCATION_ID
	WHERE B.HONORS='$dataId'
	AND B.EFFECTIVE_END_DATE > SYSDATE 
	AND D.EFFECTIVE_END_DATE > SYSDATE";
	//echo $queryID;
	$resultID = oci_parse($con,$queryID);
	oci_execute($resultID);
	$rowID = oci_fetch_row($resultID);
	$vID = $rowID[0];
	$vORG_ID = $rowID[1];
	$vLOCATION_ID = $rowID[2];
	$vLOCATION_CODE = $rowID[3];
	$vFULL_NAME = $rowID[4];
	$vSPV = $rowID[5];
	$vEMAIL_SPV = $rowID[6];
	$vMANAGER = $rowID[7];
	$vEMAIL_MANAGER = $rowID[8];
	$dataId = $vID;
	$countData = 0;
	echo $vID;
	if($vID >= 1){
		
		$queryDataId = "SELECT COUNT(-1) 
		FROM MJ.MJ_T_TIMECARD 
		WHERE STATUS = 252
		AND PERSON_ID = $vID
		AND TO_CHAR(TANGGAL, 'YYYY-MM-DD') = '$newformat'";
		$resultDataId = oci_parse($con,$queryDataId);
		oci_execute($resultDataId);
		$rowDataId = oci_fetch_row($resultDataId);
		$countData = $rowDataId[0]; 
		if($countData <= 0){
			$queryTimeCard = "INSERT INTO MJ.MJ_T_TIMECARD (ID, APP_ID, PERSON_ID, TANGGAL, JAM_MASUK, JAM_KELUAR, STATUS, STATUS_SYNC, CREATED_BY, CREATED_DATE) VALUES (MJ.MJ_T_TIMECARD_SEQ.nextval, '1', $dataId, TO_DATE('$newformat', 'YYYY-MM-DD'), '08:06', '$JamMasukAsli', '252', 'Belum', '12345', SYSDATE)";
			$result = oci_parse($con,$queryTimeCard);
			oci_execute($result);
		}
	}
}
?>