<?PHP
include '../../main/koneksi.php';
	$status ='';
	$overJam ='';
	
	
/*
	SELECT MMAP.ID
			, MMAP.PERUSAHAAN_ID
			, MMAP.HRD_ID
			, MMAP.ACCOUNTING_ID
			, MMAP.KASIR_ID
			, HOU.NAME
			, HRD.FULL_NAME
			, ACC.FULL_NAME
			, KSR.FULL_NAME
			, MMAP.STATUS
	FROM MJ.MJ_M_APPROVAL_PINJAMAN MMAP
	INNER JOIN APPS.HR_OPERATING_UNITS HOU ON HOU.ORGANIZATION_ID = MMAP.PERUSAHAAN_ID
	INNER JOIN APPS.PER_PEOPLE_F HRD ON HRD.PERSON_ID = MMAP.HRD_ID 
		AND HRD.EFFECTIVE_END_DATE > SYSDATE 
		AND HRD.CURRENT_EMPLOYEE_FLAG = 'Y'
	INNER JOIN APPS.PER_PEOPLE_F ACC ON ACC.PERSON_ID = MMAP.ACCOUNTING_ID 
		AND ACC.EFFECTIVE_END_DATE > SYSDATE 
		AND ACC.CURRENT_EMPLOYEE_FLAG = 'Y'
	INNER JOIN APPS.PER_PEOPLE_F KSR ON KSR.PERSON_ID = MMAP.KASIR_ID 
		AND KSR.EFFECTIVE_END_DATE > SYSDATE 
		AND KSR.CURRENT_EMPLOYEE_FLAG = 'Y'
*/		
	
	
	
	$result = oci_parse($con, "
		SELECT MMAP.ID
				, MMAP.PERUSAHAAN_ID
				, MMAP.HRD_ID
				, MMAP.ACCOUNTING_ID
				, MMAP.KASIR_ID
				, HOU.NAME
				, HRD.FULL_NAME
				, ACC.FULL_NAME
				, KSR.FULL_NAME
				, MMAP.STATUS
				, CKR.FULL_NAME
				, MMAP.TIPE
				, MMAP.CHECKER_ID
		FROM MJ.MJ_M_APPROVAL_PINJAMAN MMAP
		INNER JOIN APPS.HR_OPERATING_UNITS HOU ON HOU.ORGANIZATION_ID = MMAP.PERUSAHAAN_ID
		LEFT JOIN APPS.PER_PEOPLE_F HRD ON HRD.PERSON_ID = MMAP.HRD_ID 
            AND HRD.EFFECTIVE_END_DATE > SYSDATE 
            AND HRD.CURRENT_EMPLOYEE_FLAG = 'Y'
        LEFT JOIN APPS.PER_PEOPLE_F ACC ON ACC.PERSON_ID = MMAP.ACCOUNTING_ID 
            AND ACC.EFFECTIVE_END_DATE > SYSDATE 
            AND ACC.CURRENT_EMPLOYEE_FLAG = 'Y'
        LEFT JOIN APPS.PER_PEOPLE_F KSR ON KSR.PERSON_ID = MMAP.KASIR_ID 
            AND KSR.EFFECTIVE_END_DATE > SYSDATE 
            AND KSR.CURRENT_EMPLOYEE_FLAG = 'Y'
        LEFT JOIN APPS.PER_PEOPLE_F CKR ON CKR.PERSON_ID = MMAP.CHECKER_ID 
            AND CKR.EFFECTIVE_END_DATE > SYSDATE 
            AND CKR.CURRENT_EMPLOYEE_FLAG = 'Y'
	");
	oci_execute($result);
	while($row = oci_fetch_row($result))
	{
		$record = array();
		$record['HD_ID']=$row[0];
		$record['DATA_PERUSAHAANID']=$row[1];
		$record['DATA_HRDID']=$row[2];
		$record['DATA_ACCID']=$row[3];
		$record['DATA_KSRID']=$row[4];
		$record['DATA_PERUSAHAANNAME']=$row[5];
		$record['DATA_HRDNAME']=$row[6];
		$record['DATA_ACCNAME']=$row[7];
		$record['DATA_KSRNAME']=$row[8];
		
		if($row[9]=='A'){
			$status = 'ACTIVE';
		} else {
			$status = 'INACTIVE';
		}
		
		$record['DATA_CHECKER']=$row[10];
		$record['DATA_TIPE']=$row[11];
		$record['DATA_CHECKER_ID']=$row[12];
		
		$record['DATA_STATUS']=$status;
		$data[]=$record;
	}
	
echo json_encode($data); 
?>