<?PHP
include '../../main/koneksi.php';

	$result = oci_parse($con, "SELECT MMUS.ID AS HD_ID
    , MMUS.SPV_ID AS DATA_SPVID
    , MMUS.MANAGER_ID AS DATA_MANAGERID
    , MMUS.PLANT_ID AS DATA_PLANTID
	, HL.LOCATION_CODE AS DATA_NAMAPLANT
	, CASE MMUS.SPV_ID WHEN 0 THEN '' ELSE (SELECT PPFS.FULL_NAME FROM APPS.PER_PEOPLE_F PPFS WHERE PPFS.PERSON_ID=MMUS.SPV_ID AND PPFS.EFFECTIVE_END_DATE > SYSDATE) END AS DATA_NAMASPV
	, CASE MMUS.MANAGER_ID WHEN 0 THEN '' ELSE (SELECT PPFM.FULL_NAME FROM APPS.PER_PEOPLE_F PPFM WHERE PPFM.PERSON_ID=MMUS.MANAGER_ID AND PPFM.EFFECTIVE_END_DATE > SYSDATE) END AS DATA_NAMAMANAGER
    , MMUS.STATUS AS DATA_STATUS 
    FROM MJ.MJ_M_USERAPPROVAL_SPLBETON MMUS
	INNER JOIN APPS.HR_LOCATIONS HL ON HL.LOCATION_ID=MMUS.PLANT_ID
    WHERE APP_ID= " . APPCODE . "");
	oci_execute($result);
	while($row = oci_fetch_row($result))
	{
		$record = array();
		$record['HD_ID']=$row[0];
		$record['DATA_SPVID']=$row[1];
		$record['DATA_MANAGERID']=$row[2];
		$record['DATA_PLANTID']=$row[3];
		$record['DATA_NAMAPLANT']=$row[4];
		$record['DATA_NAMASPV']=$row[5];
		$record['DATA_NAMAMANAGER']=$row[6];
		$record['DATA_STATUS']=$row[7];
		$data[]=$record;
	}
	
echo json_encode($data); 
?>