<?php include '../../main/koneksi.php';

$periode1="";
$periode2="";
$queryfilter = "";
$data ="";
if (isset($_GET['periode']) || isset($_GET['nama']))
{	
	$periode = $_GET['periode'];
	$nama = $_GET['nama'];
	$dept = $_GET['dept'];
	$nama = str_replace("'", "%", $nama);

	$periode1 = substr($periode, 0, 10);
	$periode2 = substr($periode, 15, 10);

	//Edited by LFN
	$querypid = "SELECT PPF.PERSON_ID
	FROM PER_PEOPLE_F PPF
	INNER JOIN APPS.PER_ASSIGNMENTS_F PAF ON PAF.PERSON_ID=PPF.PERSON_ID
	WHERE PPF.EFFECTIVE_END_DATE > SYSDATE AND PAF.EFFECTIVE_END_DATE > SYSDATE 
	AND PAF.PRIMARY_FLAG='Y'
	AND PPF.FULL_NAME LIKE '%$nama%'";

	$resultpid = oci_parse($con,$querypid);
	oci_execute($resultpid);
	$rowpid = oci_fetch_row($resultpid);
	$pid = $rowpid[0];

	if($nama!='' AND $nama!='null'){
		$queryfilter .= " AND PERSON_ID='$pid'";
	}
	if($dept!='' AND $dept!='null'){
		$queryfilter .= " AND DEPT like'%$dept%'";
	}
} 

$countHeader = 0;
$queryHeader = "SELECT * FROM
(
	SELECT DISTINCT PPF.PERSON_ID
	, PPF.FULL_NAME AS NAMA_KARYAWAN
	, TO_CHAR(MTT.TANGGAL, 'YYYY-MM-DD') AS TANGGAL_ABSEN
	, MTT.JAM_MASUK
	, MTT.JAM_KELUAR
	, MME.ELEMENT_NAME AS KETERANGAN
	, CASE WHEN MME.ELEMENT_NAME<>'LEMBUR' THEN MTS.KATEGORI
	WHEN MME.ELEMENT_NAME='LEMBUR' THEN (CASE WHEN NVL(SPL.ID, 0)<>0 THEN 'ADA SPL' ELSE '' END) END AS SIK_SPL 
	, MTS.IJIN_KHUSUS
	, CASE WHEN MME.ELEMENT_NAME<>'LEMBUR' THEN (CASE WHEN NVL(MTS.ID, 0)<>0 AND MTS.STATUS_DOK='Approved' THEN (SELECT TO_CHAR(MTA.CREATED_DATE, 'YYYY-MM-DD')
	FROM MJ.MJ_T_APPROVAL MTA 
	WHERE MTA.TRANSAKSI_ID=MTS.ID AND MTA.APP_ID=1 AND MTA.TRANSAKSI_KODE='SIK'
	AND MTA.ID = (SELECT MAX(ID) FROM MJ.MJ_T_APPROVAL WHERE TRANSAKSI_ID=MTS.ID AND APP_ID=1 AND TRANSAKSI_KODE='SIK')) ELSE '' END)
	WHEN MME.ELEMENT_NAME='LEMBUR' THEN (CASE WHEN NVL(SPL.ID, 0)<>0 AND SPL.STATUS_DOK='Approved' THEN (SELECT TO_CHAR(MTA.CREATED_DATE, 'YYYY-MM-DD')
	FROM MJ.MJ_T_APPROVAL MTA 
	WHERE MTA.TRANSAKSI_ID=SPL.ID AND MTA.APP_ID=1 AND MTA.TRANSAKSI_KODE='SPL'
	AND MTA.ID = (SELECT MAX(ID) FROM MJ.MJ_T_APPROVAL WHERE TRANSAKSI_ID=SPL.ID AND APP_ID=1 AND TRANSAKSI_KODE='SPL')) ELSE '' END)
	ELSE '' END AS TGL_APPROVED
	, J.NAME DEPT
	FROM MJ.MJ_T_TIMECARD MTT
	INNER JOIN APPS.PER_PEOPLE_F PPF ON PPF.PERSON_ID=MTT.PERSON_ID AND PPF.EFFECTIVE_END_DATE > SYSDATE
	INNER JOIN APPS.PER_ALL_ASSIGNMENTS_F PAF ON PPF.PERSON_ID=PAF.PERSON_ID AND PAF.EFFECTIVE_END_DATE > SYSDATE AND PAF.PRIMARY_FLAG='Y'
	LEFT JOIN APPS.PER_JOBS J ON PAF.JOB_ID=J.JOB_ID
	INNER JOIN MJ.MJ_M_ELEMENT MME ON MME.ELEMENT_ID=MTT.STATUS
	LEFT JOIN MJ.MJ_T_SIK MTS ON MTS.PERSON_ID=PPF.PERSON_ID AND MTT.TANGGAL BETWEEN MTS.TANGGAL_FROM AND MTS.TANGGAL_TO AND MTS.STATUS=1 AND STATUS_DOK <> 'Disapproved'
	LEFT JOIN 
	(
		SELECT MTSPD.ID, MTSP.TANGGAL_SPL, MTSPD.PERSON_ID, MTSPD.STATUS_DOK
		FROM MJ.MJ_T_SPL MTSP
		INNER JOIN MJ.MJ_T_SPL_DETAIL MTSPD ON MTSP.ID=MTSPD.MJ_T_SPL_ID
		WHERE MTSP.STATUS=1
	) SPL ON SPL.TANGGAL_SPL=MTT.TANGGAL AND SPL.PERSON_ID=PPF.PERSON_ID
	WHERE  (MME.ELEMENT_NAME <> 'LEMBUR' OR NVL(SPL.ID, 0)<>0)
	UNION
	SELECT DISTINCT SIK.PERSON_ID
	, SIK.PEMOHON AS NAMA_KARYAWAN
	, TO_CHAR(SPL.TANGGAL_SPL, 'YYYY-MM-DD') AS TANGGAL_ABSEN
	, SPL.JAM_FROM AS JAM_MASUK
	, SPL.JAM_TO AS JAM_KELUAR
	, 'LEMBUR' AS KETERANGAN
	, 'ADA SPL' AS SIK_SPL
	, '' AS IJIN_KHUSUS
	, CASE WHEN SPL.STATUS_DOK='Approved' THEN (SELECT TO_CHAR(MTA.CREATED_DATE, 'YYYY-MM-DD')
	FROM MJ.MJ_T_APPROVAL MTA 
	WHERE MTA.TRANSAKSI_ID=SPL.ID AND MTA.APP_ID=1 AND MTA.TRANSAKSI_KODE='SPL'
	AND MTA.ID = (SELECT MAX(ID) FROM MJ.MJ_T_APPROVAL WHERE TRANSAKSI_ID=SPL.ID AND APP_ID=1 AND TRANSAKSI_KODE='SPL')) ELSE '' END AS TGL_APPROVED
	, '' AS DEPT
	FROM MJ.MJ_T_SIK SIK
	INNER JOIN
	(
		SELECT SPLD.ID, SPL.TANGGAL_SPL, SPLD.STATUS_DOK, SPLD.NAMA, SPLD.JAM_FROM, SPLD.JAM_TO, SPLD.PERSON_ID
		FROM MJ.MJ_T_SPL SPL
		INNER JOIN MJ.MJ_T_SPL_DETAIL SPLD ON SPL.ID=SPLD.MJ_T_SPL_ID
	) SPL ON SPL.PERSON_ID=SIK.PERSON_ID AND SPL.TANGGAL_SPL BETWEEN SIK.TANGGAL_FROM AND SIK.TANGGAL_TO
) KARYAWAN
WHERE TANGGAL_ABSEN >= '$periode1'
AND  TANGGAL_ABSEN <= '$periode2'
$queryfilter
ORDER BY NAMA_KARYAWAN, TANGGAL_ABSEN";

$resultHeader = oci_parse($con,$queryHeader);
oci_execute($resultHeader);
while($row = oci_fetch_row($resultHeader))
{
	$record = array();
	$record['PERSON_ID']     =$row[0];
	$record['NAMA_KARYAWAN'] =$row[1];
	$record['TANGGAL_ABSEN'] =$row[2];
	$record['JAM_MASUK']     =$row[3];
	$record['JAM_KELUAR']    =$row[4];
	$record['KETERANGAN']    =$row[5];
	$record['SIK_SPL']       =$row[6];
	$record['IJIN_KHUSUS']   =$row[7];
	$record['TGL_APPROVED']  =$row[8];
	$record['DEPT']          =$row[9];
	$data[]=$record;
}

echo json_encode($data);
?>