<?PHP
include '../../main/koneksi.php';

	$status = "";
	$result = oci_parse($con, "SELECT MPAD.ID AS HD_ID
    , MNRD.ID AS DATA_PLANT_AREA_ID
    , MNRD.PLANT_AREA AS DATA_PLANT_AREA
    , MPAD.PLANT_ID AS DATA_PLANT_ID
    , HOU.NAME AS DATA_PLANT
    , TO_CHAR(MPAD.EFFECTIVE_START_DATE, 'YYYY-MM-DD') AS DATA_START_DATE 
    , TO_CHAR(MPAD.EFFECTIVE_END_DATE, 'YYYY-MM-DD') AS DATA_END_DATE 
    , NVL(UPD.FULL_NAME, CRE.FULL_NAME) DATA_UPDATE_BY
    , NVL(TO_CHAR(MPAD.LAST_UPDATED_DATE, 'DD-MON-YYYY HH24:MI'), TO_CHAR(MPAD.CREATED_DATE, 'DD-MON-YYYY HH24:MI')) DATA_UPDATE_DATE
    , CASE WHEN TO_CHAR(SYSDATE, 'YYYYMMDD') >= TO_CHAR(MPAD.EFFECTIVE_START_DATE, 'YYYYMMDD') 
    AND TO_CHAR(SYSDATE, 'YYYYMMDD') <= TO_CHAR(NVL(MPAD.EFFECTIVE_END_DATE, TO_DATE('47121231', 'YYYYMMDD')), 'YYYYMMDD') THEN
        'ACTIVE' ELSE 'INACTIVE' END STATUS
    FROM MJ.MJ_M_PLANT_AREA_DRIVER MPAD
	INNER JOIN MJ.MJ_M_NOMINAL_RITASI_DRIVER MNRD ON MNRD.ID = MPAD.MJ_M_NOMINAL_RITASI_DRIVER_ID
	INNER JOIN APPS.HR_ORGANIZATION_UNITS HOU ON HOU.ORGANIZATION_ID = MPAD.PLANT_ID
    LEFT JOIN
    (
        SELECT MMU.ID, PPF.FULL_NAME
        FROM MJ.MJ_M_USER MMU
        INNER JOIN APPS.PER_PEOPLE_F PPF ON PPF.PERSON_ID = MMU.EMP_ID AND PPF.EFFECTIVE_END_DATE > SYSDATE AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y'
    ) UPD ON UPD.ID = MPAD.LAST_UPDATED_BY
    LEFT JOIN
    (
        SELECT MMU.ID, PPF.FULL_NAME
        FROM MJ.MJ_M_USER MMU
        INNER JOIN APPS.PER_PEOPLE_F PPF ON PPF.PERSON_ID = MMU.EMP_ID AND PPF.EFFECTIVE_END_DATE > SYSDATE AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y'
    ) CRE ON CRE.ID = MPAD.CREATED_BY
    WHERE 1=1");
	oci_execute($result);
	while($row = oci_fetch_row($result))
	{
		$record = array();
		$record['HD_ID']=$row[0];
		$record['DATA_PLANT_AREA_ID']=$row[1];
		$record['DATA_PLANT_AREA']=$row[2];
		$record['DATA_PLANT_ID']=$row[3];
		$record['DATA_PLANT']=$row[4];
		$record['DATA_START_DATE']=$row[5];
		$record['DATA_END_DATE']=$row[6];
		$record['DATA_UPDATE_BY']=$row[7];
		$record['DATA_UPDATE_DATE']=$row[8];
		$record['DATA_STATUS']=$row[9];
		$data[]=$record;
	}
	
echo json_encode($data); 
?>