<?php
include '../main/koneksi.php';

	$query = "
	SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 6), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 1), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 2), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 3), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 4), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 5), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE), 'YYYY-MM-DD') END || ' - ' ||
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE + 6), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE + 5), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE + 4), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE + 3), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE + 2), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE + 1), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 13), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 8), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 9), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 10), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 11), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 12), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 7), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 1), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 2), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 3), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 4), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 5), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 6), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 7), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 20), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 15), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 16), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 17), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 18), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 19), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 14), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 8), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 9), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 10), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 11), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 12), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 13), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 14), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 27), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 22), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 23), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 24), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 25), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 26), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 21), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 15), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 16), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 17), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 18), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 19), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 20), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 21), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 34), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 29), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 30), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 31), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 32), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 33), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 28), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 22), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 23), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 24), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 25), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 26), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 27), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 28), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 41), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 36), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 37), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 38), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 39), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 40), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 35), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 29), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 30), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 31), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 32), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 33), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 34), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 35), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 48), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 43), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 44), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 45), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 46), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 47), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 42), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 36), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 37), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 38), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 39), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 40), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 41), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 42), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 55), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 50), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 51), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 52), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 53), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 54), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 49), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 43), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 44), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 45), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 46), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 47), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 48), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 49), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 62), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 57), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 58), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 59), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 60), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 61), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 56), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 50), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 51), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 52), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 53), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 54), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 55), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 56), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 69), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 64), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 65), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 66), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 67), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 68), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 63), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 57), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 58), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 59), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 60), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 61), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 62), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 63), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 76), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 71), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 72), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 73), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 74), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 75), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 70), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 64), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 65), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 66), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 67), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 68), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 69), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 70), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 83), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 78), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 79), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 80), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 81), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 82), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 77), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 71), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 72), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 73), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 74), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 75), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 76), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 77), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
    UNION
    SELECT 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SUNDAY' THEN  TO_CHAR((SYSDATE - 90), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 85), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 86), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 87), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 88), 'YYYY-MM-DD')
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 89), 'YYYY-MM-DD')
        ELSE TO_CHAR((SYSDATE - 84), 'YYYY-MM-DD') END || ' - ' || 
        CASE WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'MONDAY' THEN  TO_CHAR((SYSDATE - 78), 'YYYY-MM-DD')  
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'TUESDAY' THEN TO_CHAR((SYSDATE - 79), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'WEDNESDAY' THEN TO_CHAR((SYSDATE - 80), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'THURSDAY' THEN TO_CHAR((SYSDATE - 81), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'FRIDAY' THEN TO_CHAR((SYSDATE - 82), 'YYYY-MM-DD') 
        WHEN TRIM(TO_CHAR(SYSDATE, 'DAY')) = 'SATURDAY' THEN TO_CHAR((SYSDATE - 83), 'YYYY-MM-DD') 
        ELSE TO_CHAR((SYSDATE - 84), 'YYYY-MM-DD')  END PERIODE
    FROM DUAL
	ORDER BY PERIODE DESC";
	$result = oci_parse($con, $query);
	oci_execute($result);
	while($row = oci_fetch_row($result))
	{
		$record = array();
		$record['DATA_VALUE']=$row[0];
		$record['DATA_NAME']=$row[0];
		$data[]=$record;
	}

	echo json_encode($data);
?>