<?PHP
include '../../main/koneksi.php';
$msgError="";
$data="";
$perusahaan="";
$departement="";
$posisi="";
$plant="";
$tglmasuk="";
$gaji = "";
$hasil = "";
$satuan = "";
$jumlah=0;
$tgldblama='2015-02-01';
$tglskr=date('Y-m-d'); 
$tahunbaru=substr($tglskr, 0, 2);
$tahunSkr=substr($tglskr, 0, 4);
$bulanSkr=substr($tglskr, 5, 2);
$hariSkr=substr($tglskr, 8, 2);

if(isset($_POST['nama_pem'])){
	$nama_pem=$_POST['nama_pem'];

	$query = "
	SELECT	DISTINCT P.PERSON_ID
			, HOU.NAME PERUSAHAAN
			, REGEXP_SUBSTR(J.NAME, '[^.]+', 1, 2) AS DEPT
			, REGEXP_SUBSTR(POS.NAME, '[^.]+', 1, 2) AS JABATAN
			, HL.LOCATION_CODE PLANT
			, TO_CHAR(P.ORIGINAL_DATE_OF_HIRE, 'YYYY-MM-DD') AS ORIGINAL_DATE_OF_HIRE
			, DECODE(A.PAYROLL_ID, NULL, '0', nvl(gp.screen_entry_value,0)) GAJI_POKOK
			, NVL(TJ.SCREEN_ENTRY_VALUE,0) TUNJ_JAB
			, NVL(TG.SCREEN_ENTRY_VALUE,0) TUNJ_GRADE
			, NVL(TL.SCREEN_ENTRY_VALUE,0) TUNJ_LOK
			, NVL(TK.SCREEN_ENTRY_VALUE,0) TUNJ_KER
			, NVL(UM.SCREEN_ENTRY_VALUE,0) UANG_MAKAN
			, NVL(UT.SCREEN_ENTRY_VALUE,0) UANG_TRANS
			, NVL(UL.SCREEN_ENTRY_VALUE,0) UANG_LEMBUR
			, NVL(BPJSKS.SCREEN_ENTRY_VALUE,0)/100*FGFKS.GLOBAL_VALUE POT_BPJS_KS
			, NVL(BPJSTK.SCREEN_ENTRY_VALUE,0)/100*FGFTK.GLOBAL_VALUE POT_BPJS_TK
			, PG.NAME GRADE
			, P.FULL_NAME
	FROM APPS.PER_PEOPLE_F P
	, APPS.PER_ALL_ASSIGNMENTS_F A
    , APPS.PER_GRADES PG
	, APPS.HR_ORGANIZATION_UNITS HOU
	, APPS.PER_JOBS J
	, APPS.FND_FLEX_VALUES_TL TL
	, APPS.PER_POSITIONS POS
	, APPS.HR_LOCATIONS HL
	, APPS.PER_PERSON_TYPES PPT
	,(SELECT  PEEF.ASSIGNMENT_ID
				,PEEF.ELEMENT_TYPE_ID
				,PET.ELEMENT_NAME
				,PIVF.NAME
				,PEEVF.SCREEN_ENTRY_VALUE
		FROM    APPS.PAY_ELEMENT_ENTRIES_F PEEF
				,APPS.PAYBV_ELEMENT_TYPE PET
				,APPS.PAY_ELEMENT_ENTRY_VALUES_F PEEVF
				,APPS.PAY_INPUT_VALUES_F PIVF
		WHERE   PEEF.ELEMENT_TYPE_ID=PET.ELEMENT_TYPE_ID
		AND     PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
		AND     PIVF.INPUT_VALUE_ID=PEEVF.INPUT_VALUE_ID
		AND     PIVF.NAME<>'Pay Value'
		AND     PET.ELEMENT_NAME='E_Gaji_Pokok'
		AND     PET.PROCESSING_TYPE='Recurring'
		AND     (SYSDATE BETWEEN PEEVF.EFFECTIVE_START_DATE AND PEEVF.EFFECTIVE_END_DATE)
		ORDER BY PEEF.ASSIGNMENT_ID) GP
	,(SELECT  PEEF.ASSIGNMENT_ID
			,PEEF.ELEMENT_TYPE_ID
			,PET.ELEMENT_NAME
			,PIVF.NAME
			,PEEVF.SCREEN_ENTRY_VALUE
	FROM    APPS.PAY_ELEMENT_ENTRIES_F PEEF
			,APPS.PAYBV_ELEMENT_TYPE PET
			,APPS.PAY_ELEMENT_ENTRY_VALUES_F PEEVF
			,APPS.PAY_INPUT_VALUES_F PIVF
	WHERE   PEEF.ELEMENT_TYPE_ID=PET.ELEMENT_TYPE_ID
	AND     PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
	AND     PIVF.INPUT_VALUE_ID=PEEVF.INPUT_VALUE_ID
	AND     PIVF.NAME<>'Pay Value'
	AND     PET.ELEMENT_NAME='E_Tunjangan_Jabatan'
	AND     PET.PROCESSING_TYPE='Recurring'
	AND     (SYSDATE BETWEEN PEEVF.EFFECTIVE_START_DATE AND PEEVF.EFFECTIVE_END_DATE)
	ORDER BY PEEF.ASSIGNMENT_ID) TJ
	,(SELECT  PEEF.ASSIGNMENT_ID
			,PEEF.ELEMENT_TYPE_ID
			,PET.ELEMENT_NAME
			,PIVF.NAME
			,PEEVF.SCREEN_ENTRY_VALUE
	FROM    APPS.PAY_ELEMENT_ENTRIES_F PEEF
			,APPS.PAYBV_ELEMENT_TYPE PET
			,APPS.PAY_ELEMENT_ENTRY_VALUES_F PEEVF
			,APPS.PAY_INPUT_VALUES_F PIVF
	WHERE   PEEF.ELEMENT_TYPE_ID=PET.ELEMENT_TYPE_ID
	AND     PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
	AND     PIVF.INPUT_VALUE_ID=PEEVF.INPUT_VALUE_ID
	AND     PIVF.NAME<>'Pay Value'
	AND     PET.ELEMENT_NAME='E_Tunjangan_Grade'
	AND     PET.PROCESSING_TYPE='Recurring'
	AND     (SYSDATE BETWEEN PEEVF.EFFECTIVE_START_DATE AND PEEVF.EFFECTIVE_END_DATE)
	ORDER BY PEEF.ASSIGNMENT_ID) TG
	,(SELECT  PEEF.ASSIGNMENT_ID
			,PEEF.ELEMENT_TYPE_ID
			,PET.ELEMENT_NAME
			,PIVF.NAME
			,PEEVF.SCREEN_ENTRY_VALUE
	FROM    APPS.PAY_ELEMENT_ENTRIES_F PEEF
			,APPS.PAYBV_ELEMENT_TYPE PET
			,APPS.PAY_ELEMENT_ENTRY_VALUES_F PEEVF
			,APPS.PAY_INPUT_VALUES_F PIVF
	WHERE   PEEF.ELEMENT_TYPE_ID=PET.ELEMENT_TYPE_ID
	AND     PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
	AND     PIVF.INPUT_VALUE_ID=PEEVF.INPUT_VALUE_ID
	AND     PIVF.NAME<>'Pay Value'
	AND     PET.ELEMENT_NAME='E_Tunjangan_Kerajinan'
	AND     PET.PROCESSING_TYPE='Recurring'
	AND     (SYSDATE BETWEEN PEEVF.EFFECTIVE_START_DATE AND PEEVF.EFFECTIVE_END_DATE)
	ORDER BY PEEF.ASSIGNMENT_ID) TK
	,(SELECT  PEEF.ASSIGNMENT_ID
			,PEEF.ELEMENT_TYPE_ID
			,PET.ELEMENT_NAME
			,PIVF.NAME
			,PEEVF.SCREEN_ENTRY_VALUE
	FROM    APPS.PAY_ELEMENT_ENTRIES_F PEEF
			,APPS.PAYBV_ELEMENT_TYPE PET
			,APPS.PAY_ELEMENT_ENTRY_VALUES_F PEEVF
			,APPS.PAY_INPUT_VALUES_F PIVF
	WHERE   PEEF.ELEMENT_TYPE_ID=PET.ELEMENT_TYPE_ID
	AND     PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
	AND     PIVF.INPUT_VALUE_ID=PEEVF.INPUT_VALUE_ID
	AND     PIVF.NAME<>'Pay Value'
	AND     PET.ELEMENT_NAME='E_Uang_Lembur'
	AND     PET.PROCESSING_TYPE='Recurring'
	AND     (SYSDATE BETWEEN PEEVF.EFFECTIVE_START_DATE AND PEEVF.EFFECTIVE_END_DATE)
	ORDER BY PEEF.ASSIGNMENT_ID) UL
	,(SELECT  PEEF.ASSIGNMENT_ID
			,PEEF.ELEMENT_TYPE_ID
			,PET.ELEMENT_NAME
			,PIVF.NAME
			,PEEVF.SCREEN_ENTRY_VALUE
	FROM    APPS.PAY_ELEMENT_ENTRIES_F PEEF
			,APPS.PAYBV_ELEMENT_TYPE PET
			,APPS.PAY_ELEMENT_ENTRY_VALUES_F PEEVF
			,APPS.PAY_INPUT_VALUES_F PIVF
	WHERE   PEEF.ELEMENT_TYPE_ID=PET.ELEMENT_TYPE_ID
	AND     PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
	AND     PIVF.INPUT_VALUE_ID=PEEVF.INPUT_VALUE_ID
	AND     PIVF.NAME<>'Pay Value'
	AND     PET.ELEMENT_NAME='E_Uang_Makan'
	AND     PET.PROCESSING_TYPE='Recurring'
	AND     (SYSDATE BETWEEN PEEVF.EFFECTIVE_START_DATE AND PEEVF.EFFECTIVE_END_DATE)
	ORDER BY PEEF.ASSIGNMENT_ID) UM
	,(SELECT  PEEF.ASSIGNMENT_ID
			,PEEF.ELEMENT_TYPE_ID
			,PET.ELEMENT_NAME
			,PIVF.NAME
			,PEEVF.SCREEN_ENTRY_VALUE
	FROM    APPS.PAY_ELEMENT_ENTRIES_F PEEF
			,APPS.PAYBV_ELEMENT_TYPE PET
			,APPS.PAY_ELEMENT_ENTRY_VALUES_F PEEVF
			,APPS.PAY_INPUT_VALUES_F PIVF
	WHERE   PEEF.ELEMENT_TYPE_ID=PET.ELEMENT_TYPE_ID
	AND     PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
	AND     PIVF.INPUT_VALUE_ID=PEEVF.INPUT_VALUE_ID
	AND     PIVF.NAME<>'Pay Value'
	AND     PET.ELEMENT_NAME='E_Uang_Transport'
	AND     PET.PROCESSING_TYPE='Recurring'
	AND     (SYSDATE BETWEEN PEEVF.EFFECTIVE_START_DATE AND PEEVF.EFFECTIVE_END_DATE)
	ORDER BY PEEF.ASSIGNMENT_ID) UT
	,(SELECT  PEEF.ASSIGNMENT_ID
			,PEEF.ELEMENT_TYPE_ID
			,PET.ELEMENT_NAME
			,PIVF.NAME
			,PEEVF.SCREEN_ENTRY_VALUE
	FROM    APPS.PAY_ELEMENT_ENTRIES_F PEEF
			,APPS.PAYBV_ELEMENT_TYPE PET
			,APPS.PAY_ELEMENT_ENTRY_VALUES_F PEEVF
			,APPS.PAY_INPUT_VALUES_F PIVF
	WHERE   PEEF.ELEMENT_TYPE_ID=PET.ELEMENT_TYPE_ID
	AND     PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
	AND     PIVF.INPUT_VALUE_ID=PEEVF.INPUT_VALUE_ID
	AND     PIVF.NAME<>'Pay Value'
	AND     PET.ELEMENT_NAME LIKE 'E_Bpjs_Ks%'
	AND     PET.PROCESSING_TYPE='Recurring'
	AND     (SYSDATE BETWEEN PEEVF.EFFECTIVE_START_DATE AND PEEVF.EFFECTIVE_END_DATE)
	ORDER BY PEEF.ASSIGNMENT_ID)BPJSKS
	,(SELECT  PEEF.ASSIGNMENT_ID
			,PEEF.ELEMENT_TYPE_ID
			,PET.ELEMENT_NAME
			,PIVF.NAME
			,PEEVF.SCREEN_ENTRY_VALUE
	FROM    APPS.PAY_ELEMENT_ENTRIES_F PEEF
			,APPS.PAYBV_ELEMENT_TYPE PET
			,APPS.PAY_ELEMENT_ENTRY_VALUES_F PEEVF
			,APPS.PAY_INPUT_VALUES_F PIVF
	WHERE   PEEF.ELEMENT_TYPE_ID=PET.ELEMENT_TYPE_ID
	AND     PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
	AND     PIVF.INPUT_VALUE_ID=PEEVF.INPUT_VALUE_ID
	AND     PIVF.NAME<>'Pay Value'
	AND     PET.ELEMENT_NAME LIKE 'E_Bpjs_Tk%'
	AND     PET.PROCESSING_TYPE='Recurring'
	AND     (SYSDATE BETWEEN PEEVF.EFFECTIVE_START_DATE AND PEEVF.EFFECTIVE_END_DATE)
	ORDER BY PEEF.ASSIGNMENT_ID) BPJSTK
	,(SELECT  PEEF.ASSIGNMENT_ID
			,PEEF.ELEMENT_TYPE_ID
			,PET.ELEMENT_NAME
			,PIVF.NAME
			,PEEVF.SCREEN_ENTRY_VALUE
	FROM    APPS.PAY_ELEMENT_ENTRIES_F PEEF
			,APPS.PAYBV_ELEMENT_TYPE PET
			,APPS.PAY_ELEMENT_ENTRY_VALUES_F PEEVF
			,APPS.PAY_INPUT_VALUES_F PIVF
	WHERE   PEEF.ELEMENT_TYPE_ID=PET.ELEMENT_TYPE_ID
	AND     PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
	AND     PIVF.INPUT_VALUE_ID=PEEVF.INPUT_VALUE_ID
	AND     PIVF.NAME<>'Pay Value'
	AND     PET.ELEMENT_NAME='E_PPH_21'
	AND     PET.PROCESSING_TYPE='Recurring'
	AND     (SYSDATE BETWEEN PEEVF.EFFECTIVE_START_DATE AND PEEVF.EFFECTIVE_END_DATE)
	ORDER BY PEEF.ASSIGNMENT_ID) PPH
	,(SELECT  PEEF.ASSIGNMENT_ID
			,PEEF.ELEMENT_TYPE_ID
			,PET.ELEMENT_NAME
			,PIVF.NAME
			,PEEVF.SCREEN_ENTRY_VALUE
	FROM    APPS.PAY_ELEMENT_ENTRIES_F PEEF
			,APPS.PAYBV_ELEMENT_TYPE PET
			,APPS.PAY_ELEMENT_ENTRY_VALUES_F PEEVF
			,APPS.PAY_INPUT_VALUES_F PIVF
	WHERE   PEEF.ELEMENT_TYPE_ID=PET.ELEMENT_TYPE_ID
	AND     PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
	AND     PIVF.INPUT_VALUE_ID=PEEVF.INPUT_VALUE_ID
	AND     PIVF.NAME<>'Pay Value'
	AND     PET.ELEMENT_NAME='E_Tunjangan_Lokasi'
	AND     PET.PROCESSING_TYPE='Recurring'
	AND     (SYSDATE BETWEEN PEEVF.EFFECTIVE_START_DATE AND PEEVF.EFFECTIVE_END_DATE)
	ORDER BY PEEF.ASSIGNMENT_ID) TL
	, APPS.FF_GLOBALS_F FGFTK
	, APPS.FF_GLOBALS_F FGFKS
	WHERE   P.PERSON_ID=A.PERSON_ID
	AND     P.PERSON_ID=$nama_pem
    AND     A.GRADE_ID = PG.GRADE_ID
	AND     A.JOB_ID=J.JOB_ID(+)
	AND     REGEXP_SUBSTR(J.NAME, '[^.]+', 1, 1)=TL.FLEX_VALUE_MEANING(+)
	AND     A.POSITION_ID=POS.POSITION_ID(+)
	AND     A.LOCATION_ID=HL.LOCATION_ID(+)
	AND     SYSDATE BETWEEN P.EFFECTIVE_START_DATE AND P.EFFECTIVE_END_DATE
	AND     (SYSDATE-5) BETWEEN NVL(A.EFFECTIVE_START_DATE,SYSDATE) AND NVL(A.EFFECTIVE_END_DATE,SYSDATE)
	AND     LOWER(P.LAST_NAME) NOT LIKE '%trial%'
	AND     GP.ASSIGNMENT_ID(+)=A.ASSIGNMENT_ID
	AND     TJ.ASSIGNMENT_ID(+)=A.ASSIGNMENT_ID
	AND     TG.ASSIGNMENT_ID(+)=A.ASSIGNMENT_ID
	AND     TK.ASSIGNMENT_ID(+)=A.ASSIGNMENT_ID
	AND     UL.ASSIGNMENT_ID(+)=A.ASSIGNMENT_ID
	AND     UM.ASSIGNMENT_ID(+)=A.ASSIGNMENT_ID
	AND     UT.ASSIGNMENT_ID(+)=A.ASSIGNMENT_ID
	AND     BPJSKS.ASSIGNMENT_ID(+)=A.ASSIGNMENT_ID
	AND     BPJSTK.ASSIGNMENT_ID(+)=A.ASSIGNMENT_ID
	AND     PPH.ASSIGNMENT_ID(+)=A.ASSIGNMENT_ID
	AND     TL.ASSIGNMENT_ID(+)=A.ASSIGNMENT_ID
	AND     PPT.PERSON_TYPE_ID(+)=P.PERSON_TYPE_ID
	AND     PPT.USER_PERSON_TYPE<>'Ex-employee'
	AND     A.PRIMARY_FLAG='Y'
	AND     A.PEOPLE_GROUP_ID <> 3061
	AND     P.CURRENT_EMPLOYEE_FLAG = 'Y'
	AND     A.ORGANIZATION_ID = HOU.ORGANIZATION_ID
	ORDER BY P.PERSON_ID
	";

	/*
	AND     NVL(GP.SCREEN_ENTRY_VALUE,0)<>0
	AND     A.PAYROLL_ID IS NOT NULL
	AND     TRIM(REGEXP_SUBSTR(FGFTK.GLOBAL_DESCRIPTION, '[^ ]+', 1, 2))=TRIM(REGEXP_SUBSTR(BPJSTK.ELEMENT_NAME, '[^_]+', 1, 4))
	AND     TRIM(REGEXP_SUBSTR(FGFKS.GLOBAL_DESCRIPTION, '[^ ]+', 1, 2))=TRIM(REGEXP_SUBSTR(BPJSKS.ELEMENT_NAME, '[^_]+', 1, 4))
	and     hl.location_code in ('Barata 46', 'Pataya', 'Ruko Kuning','Jakarta','Sanur')
	*/
	
	// echo $query; exit;
	
	$result = oci_parse($con, $query);
	oci_execute($result);
	
	while($row = oci_fetch_row($result))
	{
		$perusahaan = $row[1];
		$departement = $row[2];
		$posisi = $row[3];
		$plant = $row[4];
		$grade = $row[16];
		$nama_existing = $row[17];
		
		$gaji = $row[6]+$row[7]+$row[10]+($row[11]*25)+($row[12]*25);



/*		
		$query = "SELECT DISTINCT MTP.ID
		, MTP.PERSON_ID
		, MTP.TIPE
		, TO_CHAR(MTP.TANGGAL_PINJAMAN, 'YYYY-MM-DD') TGL_PINJAMAN
		, MTP.NOMINAL JML_CICILAN_P
		, MTP.JUMLAH_CICILAN
		, (MTP.NOMINAL*MTP.JUMLAH_CICILAN_AWAL) NOMINAL
		, ( MTP.NOMINAL * MTP.JUMLAH_CICILAN_AWAL )
		 - NVL (
			  (SELECT SUM (NOMINAL)
				 FROM MJ_T_PINJAMAN_DETAIL
				WHERE     MJ_T_PINJAMAN_ID = MTP.ID
					  AND TAHUN <= '$tahunSkr'
					  AND BULAN <= '$bulanSkr' ),
			  0 )
			OUTSTANDING
		, MTP.JUMLAH_CICILAN_AWAL - (SELECT COUNT(-1) FROM MJ_T_PINJAMAN_DETAIL
			WHERE MJ_T_PINJAMAN_ID=MTP.ID
			AND TAHUN <= '$tahunSkr'
			AND BULAN <= '$bulanSkr') OUTSTANDING_BLN
		, NVL(MTPD.BULAN||' '||MTPD.TAHUN,'-') BULAN
		, TO_CHAR(MTP.CREATED_DATE, 'YYYY-MM-DD') TGL_PEMBUATAN
		, MTP.STATUS_DOKUMEN
		, PPF.FULL_NAME APP_TERAKHIR
		FROM MJ.MJ_T_PINJAMAN MTP
		LEFT JOIN MJ.MJ_T_APPROVAL MTA ON MTP.ID = MTA.TRANSAKSI_ID AND TRANSAKSI_KODE = 'PINJAMAN' AND MTA.TINGKAT = (MTP.TINGKAT-1)
		LEFT JOIN PER_PEOPLE_F PPF ON MTA.EMP_ID = PPF.PERSON_ID AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y' AND PPF.EFFECTIVE_END_DATE > SYSDATE
		LEFT JOIN MJ.MJ_T_PINJAMAN_DETAIL MTPD ON MTP.ID = MTPD.MJ_T_PINJAMAN_ID 
		WHERE MTP.PERSON_ID=$nama_pem 
		AND MTP.JUMLAH_CICILAN != 0
		AND ((MTP.TIPE = 'PINJAMAN PERSONAL' and MTP.STATUS_DOKUMEN = 'Validate') or (MTP.TIPE = 'PINJAMAN PENGGANTI INVENTARIS' and MTP.STATUS_DOKUMEN = 'Approved'))
		ORDER BY MTP.ID";
*/

		$query = "
		  SELECT DISTINCT
				 MTP.ID,
				 MTP.PERSON_ID,
				 MTP.TIPE,
				 TO_CHAR (MTP.TANGGAL_PINJAMAN, 'YYYY-MM-DD') TGL_PINJAMAN,
				 MTP.NOMINAL JML_CICILAN_P,
				 MTP.JUMLAH_CICILAN,
				 (MTP.NOMINAL * MTP.JUMLAH_CICILAN_AWAL) NOMINAL,
				   (MTP.NOMINAL * MTP.JUMLAH_CICILAN_AWAL)
				 - NVL (
					  (SELECT SUM (NOMINAL)
						 FROM MJ_T_PINJAMAN_DETAIL
						WHERE     MJ_T_PINJAMAN_ID = MTP.ID
							  --AND TAHUN <= '$tahunSkr'
							  --AND BULAN <= '$bulanSkr' 
						),
					  0)
					OUTSTANDING,
				   MTP.JUMLAH_CICILAN_AWAL
				 - (SELECT COUNT (-1)
					  FROM MJ_T_PINJAMAN_DETAIL
					 WHERE     MJ_T_PINJAMAN_ID = MTP.ID
						   --AND TAHUN <= '$tahunSkr'
						   --AND BULAN <= '$bulanSkr' 
					)
					OUTSTANDING_BLN,
				 TO_CHAR (MTP.CREATED_DATE, 'YYYY-MM-DD') TGL_PEMBUATAN,
				 MTP.STATUS_DOKUMEN,
				 PPF.FULL_NAME APP_TERAKHIR
			FROM MJ.MJ_T_PINJAMAN MTP
				 LEFT JOIN MJ.MJ_T_APPROVAL MTA
					ON     MTP.ID = MTA.TRANSAKSI_ID
					   AND TRANSAKSI_KODE = 'PINJAMAN'
					   AND MTA.TINGKAT = (MTP.TINGKAT - 1)
				 LEFT JOIN APPS.PER_PEOPLE_F PPF
					ON     MTA.EMP_ID = PPF.PERSON_ID
					   AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y'
					   AND PPF.EFFECTIVE_END_DATE > SYSDATE
		   WHERE     MTP.PERSON_ID = $nama_pem 
				 AND MTP.JUMLAH_CICILAN != 0
				 AND (   (    MTP.TIPE = 'PINJAMAN PERSONAL'
						  AND MTP.STATUS_DOKUMEN = 'Validate')
					  OR (    MTP.TIPE = 'PINJAMAN PENGGANTI INVENTARIS'
						  AND MTP.STATUS_DOKUMEN = 'Approved'))
		ORDER BY MTP.ID
		";
		
	
		// echo $query;exit;
		
		$result = oci_parse($con,$query);
		oci_execute($result);
		while($row = oci_fetch_row($result))
		{
			$jumlah = $jumlah + $row[7];
		}
		
	}
	
$hasil = $perusahaan . "|" . $departement . "|" . $posisi . "|" . $plant . "|" . $grade . "|" . number_format($gaji, 2, ',', '.') . "|" . $gaji . "|" . $jumlah . "|" . $nama_existing;
}

$result = array('success' => true,
			'results' => $hasil,
			'rows' => ''
		);
echo json_encode($result);

?>