<?php
include '../../main/koneksi.php';

$periode1="";
$periode2="";
$queryfilter = "";
if (isset($_GET['bulan']) || isset($_GET['nama']))
{	
	$bulan = $_GET['bulan'];
	$tahun = $_GET['tahun'];
	$nama = $_GET['nama'];
	$dept = $_GET['dept'];
	if($nama!=''){
		$queryfilter .= " AND PPF.FULL_NAME='$nama'";
	}
	if($dept!=''){
		$queryfilter .= " AND REGEXP_SUBSTR(PJ.NAME, '[^.]+', 1, 3)='$dept'";
	}
} 


 $namaFile ="Report_Karyawan.xls";

// Function penanda awal file (Begin Of File) Excel

function xlsBOF() {
echo pack("ssssss", 0x809, 0x8, 0x0, 0x10, 0x0, 0x0);
return;
}

// Function penanda akhir file (End Of File) Excel

function xlsEOF() {
echo pack("ss", 0x0A, 0x00);
return;
}

// Function untuk menulis data (angka) ke cell excel

function xlsWriteNumber($Row, $Col, $Value) {
echo pack("sssss", 0x203, 14, $Row, $Col, 0x0);
echo pack("d", $Value);
return;
}

// Function untuk menulis data (text) ke cell excel

function xlsWriteLabel($Row, $Col, $Value ) {
$L = strlen($Value);
echo pack("ssssss", 0x204, 8 + $L, $Row, $Col, 0x0, $L);
echo $Value;
return;
}

// header file excel
header("Status: 200");
	header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
	header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT');
	header("Pragma: hack");
	header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
	header("Cache-Control: private", false);
	header("Content-Description: File Transfer");
	header("Content-Type: application/force-download");
	header("Content-Type: application/download");
	header("Content-Disposition: attachment; filename=\"".$namaFile."\""); 
	header("Content-Transfer-Encoding: binary");


$isiExcel = "<table border=\"0\">
<tr>
    <td colspan=\"13\"><div align=\"center\">Report Gaji Potongan</div></td>
</tr>
<tr>
    <td><div align=\"center\">No</div></td>
    <td><div align=\"center\">Nomor Karyawan</div></td>
    <td><div align=\"center\">Nama Karyawan</div></td>
    <td><div align=\"center\">Nomor Rekening</div></td>
    <td><div align=\"center\">Atas Nama</div></td>
    <td><div align=\"center\">Hari Alpha</div></td>
    <td><div align=\"center\">Total Alpha</div></td>
    <td><div align=\"center\">Hari Terlambat</div></td>
    <td><div align=\"center\">Total Terlambat</div></td>
    <td><div align=\"center\">Hari Ijin</div></td>
    <td><div align=\"center\">Total Ijin</div></td>
 </tr>
 
 ";
 
	$countHeader = 0;
	$queryHeader = "SELECT  DISTINCT 
        PPF.EMPLOYEE_NUMBER
        ,PPF.FULL_NAME
        ,TRIM(REGEXP_SUBSTR(PPF.PREVIOUS_LAST_NAME, '[^-]+', 1, 2)) AS NO_REKENING
        ,TRIM(REGEXP_SUBSTR(PPF.PREVIOUS_LAST_NAME, '[^-]+', 1, 3)) AS ATAS_NAMA
        ,NVL(TA.TOTAL_ALPHA, 0) AS HARI_ALPHA
        ,CAST(NVL(UTOT.UANG_TOTAL, 0) AS DECIMAL) AS TOTAL_ALPHA
        ,NVL(TT.TOTAL_TERLAMBAT, 0) AS HARI_TERLAMBAT
        , CAST(NVL(PT.UANG_TOTAL, 0) AS DECIMAL) AS TOTAL_TERLAMBAT
        ,NVL(TI.TOTAL_IJIN, 0) AS HARI_IJIN
        ,CAST(NVL(UTOT1.UANG_TOTAL, 0) AS DECIMAL) AS TOTAL_IJIN
		FROM    APPS.PER_PEOPLE_F PPF
        ,APPS.PER_ASSIGNMENTS_F PAF
        ,APPS.PER_JOBS PJ
        ,APPS.PER_POSITIONS PP
        ,APPS.HR_LOCATIONS HL
        ,MJ.MJ_T_POTONGAN MTP
        ,(SELECT DISTINCT PAPF.PERSON_ID, PRRV.RESULT_VALUE AS GAJI_POKOK
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Gaji_Pokok' AND PIV.NAME='Gaji Pokok') GP
        ,(SELECT DISTINCT PAPF.PERSON_ID, PRRV.RESULT_VALUE AS UANG_MAKAN
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Uang_Makan' AND PIV.NAME='Uang Makan') UM 
        ,(SELECT DISTINCT PAPF.PERSON_ID, PRRV.RESULT_VALUE AS UANG_TRANSPORT
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Uang_Transport' AND PIV.NAME='Uang Transport') UT 
        ,(SELECT DISTINCT PAPF.PERSON_ID, PRRV.RESULT_VALUE AS UANG_TUNJAB
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Tunjangan_Jabatan' AND PIV.NAME='Tunjangan Jabatan') UTJ 
        ,(SELECT DISTINCT PAPF.PERSON_ID, PRRV.RESULT_VALUE AS UANG_TUNLOK
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Tunjangan_Lokasi' AND PIV.NAME='Tunjangan Lokasi') UTL 
        ,(SELECT DISTINCT PAPF.PERSON_ID, PRRV.RESULT_VALUE AS UANG_TUNGRADE
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Tunjangan_Grade' AND PIV.NAME='Tunjangan Grade') UTG 
        ,(SELECT DISTINCT PAPF.PERSON_ID, PRRV.RESULT_VALUE AS BPJS_KESEHATAN
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME LIKE 'E_Bpjs_Ks%' AND PIV.NAME='Pay Value') BKS 
        ,(SELECT DISTINCT PAPF.PERSON_ID, PRRV.RESULT_VALUE AS BPJS_TENAGAKERJA
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME LIKE 'E_Bpjs_Tk%' AND PIV.NAME='Pay Value') BTK
        ,(SELECT DISTINCT PAPF.PERSON_ID, PRRV.RESULT_VALUE AS POTONGAN_PPH
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_PPH_21' AND PIV.NAME='Pay Value') PPH
        ,(SELECT DISTINCT PAPF.PERSON_ID, PRRV.RESULT_VALUE AS UANG_TUNKER
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Tunjangan_Kerajinan' AND PIV.NAME='Pay Value') UTK
        ,(SELECT PAPF.PERSON_ID, SUM(PRRV.RESULT_VALUE) AS UANG_TOTAL
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME IN ('E_Alpha') AND PIV.NAME='Potongan'
        GROUP BY PAPF.PERSON_ID) UTOT
        ,(SELECT PAPF.PERSON_ID, SUM(PRRV.RESULT_VALUE) AS UANG_TOTAL
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME IN ('E_Ijin') AND PIV.NAME='Potongan'
        GROUP BY PAPF.PERSON_ID) UTOT1
        ,(SELECT PAPF.PERSON_ID, SUM(PRRV.RESULT_VALUE) AS UANG_TOTAL
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME ='E_Terlambat' AND PIV.NAME='Potongan'
        GROUP BY PAPF.PERSON_ID) PT
        ,(SELECT PAPF.PERSON_ID, SUM(PRRV.RESULT_VALUE) AS UANG_TOTAL
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Lembur' AND PIV.NAME='Pay Value'
        GROUP BY PAPF.PERSON_ID) UL
        ,(SELECT PAPF.PERSON_ID, COUNT(-1) AS TOTAL_IJIN
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE   
        PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Ijin' AND PIV.NAME='Hours'
        GROUP BY PAPF.PERSON_ID) TI
        ,(SELECT PAPF.PERSON_ID, COUNT(-1) AS TOTAL_MASUK
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE   
        PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Masuk' AND PIV.NAME='Hours'
        GROUP BY PAPF.PERSON_ID) TM
        ,(SELECT PAPF.PERSON_ID, COUNT(-1) AS TOTAL_ALPHA
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE   --ppa.payroll_action_id = :payroll_action_id -- give your payroll_action_id
        PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Alpha' AND PIV.NAME='Hours'
        GROUP BY PAPF.PERSON_ID) TA
        ,(SELECT PAPF.PERSON_ID, COUNT(-1) AS TOTAL_TERLAMBAT
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE   --ppa.payroll_action_id = :payroll_action_id -- give your payroll_action_id
        PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Terlambat' AND PIV.NAME='Hours'
        GROUP BY PAPF.PERSON_ID) TT
        ,(SELECT PAPF.PERSON_ID, COUNT(-1) AS TOTAL_CUTI
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE   
        PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Cuti' AND PIV.NAME='Hours'
        GROUP BY PAPF.PERSON_ID) TC
        ,(SELECT PAPF.PERSON_ID, COUNT(-1) AS TOTAL_SAKIT
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE   
        PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Sakit' AND PIV.NAME='Hours'
        GROUP BY PAPF.PERSON_ID) TS
        ,(SELECT PAPF.PERSON_ID, PRRV.RESULT_VALUE AS UANG_REVGAJ
         FROM APPS.PAY_PAYROLL_ACTIONS PPA
        ,APPS.PAY_ASSIGNMENT_ACTIONS PAA
        ,APPS.PAY_PAYROLLS_F PP
        ,APPS.PAY_RUN_RESULTS PRR
        ,APPS.PAY_RUN_RESULT_VALUES PRRV
        ,APPS.PAY_INPUT_VALUES_F PIV
        ,APPS.PAY_ELEMENT_TYPES_F PET
        ,APPS.PER_ALL_ASSIGNMENTS_F PAAF
        ,APPS.PER_ALL_PEOPLE_F PAPF
        WHERE  PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
        AND PPA.PAYROLL_ID = PP.PAYROLL_ID
        AND PAA.ASSIGNMENT_ACTION_ID = PRR.ASSIGNMENT_ACTION_ID
        AND PRR.RUN_RESULT_ID= PRRV.RUN_RESULT_ID
        AND PRRV.INPUT_VALUE_ID = PIV.INPUT_VALUE_ID
        AND PIV.ELEMENT_TYPE_ID = PET.ELEMENT_TYPE_ID
        AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
        AND PAAF.PERSON_ID = PAPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PP.EFFECTIVE_START_DATE AND PP.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PET.EFFECTIVE_START_DATE AND PET.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PIV.EFFECTIVE_START_DATE AND PIV.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
        AND TRIM(TO_CHAR(PPA.EFFECTIVE_DATE,'Month')) || TO_CHAR(PPA.EFFECTIVE_DATE,'-YYYY')='$bulan-$tahun'
        AND PET.ELEMENT_NAME='E_Revisi_Gaji' AND PIV.NAME='Pay Value'
        ORDER BY EMPLOYEE_NUMBER) URG
WHERE   PAF.PERSON_ID=PPF.PERSON_ID
        AND PAF.JOB_ID=PJ.JOB_ID
        AND PAF.POSITION_ID=PP.POSITION_ID
        AND PAF.LOCATION_ID=HL.LOCATION_ID
        AND GP.PERSON_ID=PPF.PERSON_ID
        AND UM.PERSON_ID=PPF.PERSON_ID
        AND UT.PERSON_ID=PPF.PERSON_ID
        AND UTJ.PERSON_ID=PPF.PERSON_ID
        AND UTL.PERSON_ID(+)=PPF.PERSON_ID
        AND UTG.PERSON_ID=PPF.PERSON_ID
        AND BKS.PERSON_ID(+)=PPF.PERSON_ID
        AND BTK.PERSON_ID(+)=PPF.PERSON_ID
        AND PPH.PERSON_ID(+)=PPF.PERSON_ID
        AND UTK.PERSON_ID(+)=PPF.PERSON_ID
        AND UTOT.PERSON_ID(+)=PPF.PERSON_ID
        AND UTOT1.PERSON_ID(+)=PPF.PERSON_ID
        AND TM.PERSON_ID(+)=PPF.PERSON_ID
        AND TC.PERSON_ID(+)=PPF.PERSON_ID
        AND TA.PERSON_ID(+)=PPF.PERSON_ID
        AND TT.PERSON_ID(+)=PPF.PERSON_ID
        AND TI.PERSON_ID(+)=PPF.PERSON_ID
        AND TS.PERSON_ID(+)=PPF.PERSON_ID
        AND MTP.PERSON_ID(+)=PPF.PERSON_ID
        AND PT.PERSON_ID(+)=PPF.PERSON_ID
        AND UL.PERSON_ID(+)=PPF.PERSON_ID
        AND URG.PERSON_ID(+)=PPF.PERSON_ID
        AND TRUNC(SYSDATE) BETWEEN PPF.EFFECTIVE_START_DATE AND PPF.EFFECTIVE_END_DATE
        AND TRUNC(SYSDATE) BETWEEN PAF.EFFECTIVE_START_DATE AND PAF.EFFECTIVE_END_DATE
        AND TRIM(REGEXP_SUBSTR(PPF.PREVIOUS_LAST_NAME, '[^-]+', 1, 2)) IS NOT NULL
        --AND NVL(PAF.PEOPLE_GROUP_ID,0) <> 1061
        AND PAF.PAYROLL_ID IS NOT NULL
        AND (CAST(NVL(UTOT.UANG_TOTAL, 0) AS DECIMAL)
        + CAST(NVL(PT.UANG_TOTAL, 0) AS DECIMAL)) > 0
		$queryfilter
		ORDER BY PPF.FULL_NAME";
	//echo $queryHeader;
	$resultHeader = oci_parse($con,$queryHeader);
	oci_execute($resultHeader);
	while($row = oci_fetch_row($resultHeader))
	{
		$countHeader++;
		$nomorKaryawan = $row[0];
		$namaKaryawan = $row[1];
		$noReg = $row[2];
		$AtasNama = $row[3];
		$hariAlpha = $row[4];
		$totAlpha = $row[5];
		$hariTerlambat = $row[6];
		$totTerlambat = $row[7];
		$hariIjin = $row[8];
		$totIjin = $row[9];
		$isiExcel .= "
		<tr>
			<td><div align=\"center\">$countHeader</div></td>
			<td><div align=\"left\">$nomorKaryawan</div></td>
			<td><div align=\"left\">$namaKaryawan</div></td>
			<td><div align=\"left\">$noReg</div></td>
			<td><div align=\"left\">$AtasNama</div></td>
			<td><div align=\"left\">$hariAlpha</div></td>
			<td><div align=\"left\">$totAlpha</div></td>
			<td><div align=\"left\">$hariTerlambat</div></td>
			<td><div align=\"left\">$totTerlambat</div></td>
			<td><div align=\"left\">$hariIjin</div></td>
			<td><div align=\"left\">$totIjin</div></td>
		 </tr>
		 ";		
	}
$isiExcel .= " </table>";
	
$fp = fopen($namaFile, "w");
fwrite($fp, $isiExcel);

fclose($fp);

header('Content-Length: ' . filesize($namaFile));
readfile($namaFile);

exit();

?>