

SELECT  *
FROM    MJ_M_UPLOAD
ORDER   BY CREATEDDATE DESC


SELECT  *
FROM    MJ_TEMP_UPLOAD
ORDER   BY CREATEDDATE DESC


SELECT  COUNT(-1) 
FROM    MJ.MJ_SYS_USER_RULE MSUR 
INNER   JOIN MJ.MJ_SYS_RULE MSR ON MSR.ID_RULE=MSUR.ID_RULE 
WHERE   1 = 1

AND     MSUR.ID_USER = 38170  --$user_id 

AND     MSUR.AKTIF = 'Y'
AND     MSR.AKTIF = 'Y' 


AND MSR.APP_ID= " . APPCODE . " 
AND NAMA_RULE='Administrator'



SELECT MTM.ID
, MTM.NO_REQUEST
, MTM.TIPE
, PPF1.FULL_NAME PEMBUAT
, PPF.FULL_NAME KARYAWAN
, PJ.NAME DEPT_LAMA
, PP.NAME POSISI_LAMA
, HL.LOCATION_CODE LOKASI_LAMA
, MTM.GAJI_LAMA
, PJ1.NAME DEPT_BARU
, PP1.NAME POSISI_BARU
, HL1.LOCATION_CODE LOKASI_BARU
, MTM.GAJI_BARU
, MTM.KETERANGAN
, MTM.ALASAN
, TO_CHAR(MTM.TGL_EFFECTIVE, 'YYYY-MM-DD')
, PVG.NAME GRADE_LAMA
, PVG1.NAME GRADE
, PPF3.FIRST_NAME || ' ' || PPF3.LAST_NAME MGR_LAMA
, PPF4.FIRST_NAME || ' ' || PPF4.LAST_NAME MGR_BARU
, MTM.STATUS_KARYAWAN
, MTM.SIFAT_PERUBAHAN
, MTM.JUMLAH_BULAN
FROM MJ.MJ_T_MUTASI MTM
INNER JOIN APPS.PER_PEOPLE_F PPF ON PPF.PERSON_ID = MTM.KARYAWAN_ID AND PPF.EFFECTIVE_END_DATE > SYSDATE
INNER JOIN APPS.PER_PEOPLE_F PPF1 ON PPF1.PERSON_ID = MTM.CREATED_BY AND PPF1.EFFECTIVE_END_DATE > SYSDATE
LEFT JOIN APPS.PER_PEOPLE_F PPF3 ON PPF3.PERSON_ID = MTM.MGR_LAMA AND PPF3.EFFECTIVE_END_DATE > SYSDATE
LEFT JOIN APPS.PER_PEOPLE_F PPF4 ON PPF4.PERSON_ID = MTM.MGR_BARU AND PPF4.EFFECTIVE_END_DATE > SYSDATE
LEFT JOIN APPS.PER_JOBS PJ ON PJ.JOB_ID = MTM.DEPT_LAMA_ID
LEFT JOIN APPS.PER_POSITIONS PP ON PP.POSITION_ID = MTM.POSISI_LAMA_ID
LEFT JOIN APPS.PER_VALID_GRADES_V PVG ON PVG.POSITION_ID=PP.POSITION_ID
LEFT JOIN APPS.HR_LOCATIONS HL ON HL.LOCATION_ID = MTM.LOKASI_LAMA_ID 
LEFT JOIN APPS.PER_JOBS PJ1 ON PJ1.JOB_ID = MTM.DEPT_BARU_ID
LEFT JOIN APPS.PER_POSITIONS PP1 ON PP1.POSITION_ID = MTM.POSISI_BARU_ID
LEFT JOIN APPS.PER_VALID_GRADES_V PVG1 ON PVG1.POSITION_ID=PP1.POSITION_ID
LEFT JOIN APPS.HR_LOCATIONS HL1 ON HL1.LOCATION_ID = MTM.LOKASI_BARU_ID 
WHERE 1=1
AND MTM.STATUS_DOK NOT IN ('Approved','Disapproved') AND MTM.TINGKAT IN (0, 1)

* * * * *


PVG1.POSITION_ID, PP1.POSITION_ID,

SELECT MTM.ID
, MTM.NO_REQUEST
, MTM.TIPE
, PPF1.FULL_NAME PEMBUAT
, PPF.FULL_NAME KARYAWAN
, PJ.NAME DEPT_LAMA
, PP.NAME POSISI_LAMA
, HL.LOCATION_CODE LOKASI_LAMA
, MTM.GAJI_LAMA
, PJ1.NAME DEPT_BARU
, PP1.NAME POSISI_BARU
, HL1.LOCATION_CODE LOKASI_BARU
, MTM.GAJI_BARU
, MTM.KETERANGAN
, MTM.ALASAN
, TO_CHAR(MTM.TGL_EFFECTIVE, 'YYYY-MM-DD')
, PVG.NAME GRADE_LAMA
, PVG1.NAME GRADE
, PPF3.FIRST_NAME || ' ' || PPF3.LAST_NAME MGR_LAMA
, PPF4.FIRST_NAME || ' ' || PPF4.LAST_NAME MGR_BARU
, MTM.STATUS_KARYAWAN
, MTM.SIFAT_PERUBAHAN
, MTM.JUMLAH_BULAN
FROM MJ.MJ_T_MUTASI MTM
INNER JOIN APPS.PER_PEOPLE_F PPF ON PPF.PERSON_ID = MTM.KARYAWAN_ID AND PPF.EFFECTIVE_END_DATE > SYSDATE
INNER JOIN APPS.PER_PEOPLE_F PPF1 ON PPF1.PERSON_ID = MTM.CREATED_BY AND PPF1.EFFECTIVE_END_DATE > SYSDATE
LEFT JOIN APPS.PER_PEOPLE_F PPF3 ON PPF3.PERSON_ID = MTM.MGR_LAMA AND PPF3.EFFECTIVE_END_DATE > SYSDATE
LEFT JOIN APPS.PER_PEOPLE_F PPF4 ON PPF4.PERSON_ID = MTM.MGR_BARU AND PPF4.EFFECTIVE_END_DATE > SYSDATE
LEFT JOIN APPS.PER_JOBS PJ ON PJ.JOB_ID = MTM.DEPT_LAMA_ID
LEFT JOIN APPS.PER_POSITIONS PP ON PP.POSITION_ID = MTM.POSISI_LAMA_ID
LEFT JOIN APPS.PER_VALID_GRADES_V PVG ON PVG.POSITION_ID=PP.POSITION_ID
LEFT JOIN APPS.HR_LOCATIONS HL ON HL.LOCATION_ID = MTM.LOKASI_LAMA_ID 
LEFT JOIN APPS.PER_JOBS PJ1 ON PJ1.JOB_ID = MTM.DEPT_BARU_ID
LEFT JOIN APPS.PER_POSITIONS PP1 ON PP1.POSITION_ID = MTM.POSISI_BARU_ID
LEFT JOIN APPS.PER_VALID_GRADES_V PVG1 ON PVG1.POSITION_ID = PP1.POSITION_ID AND PVG1.GRADE_ID = MTM.GRADE_BARU_ID
LEFT JOIN APPS.HR_LOCATIONS HL1 ON HL1.LOCATION_ID = MTM.LOKASI_BARU_ID 
WHERE 1=1
AND MTM.STATUS_DOK NOT IN ('Approved','Disapproved') AND MTM.TINGKAT IN (0, 1)



SELECT  *
FROM    APPS.PER_VALID_GRADES_V 
WHERE   POSITION_ID = 115065

* * * * *


SELECT MTM.ID
, MTM.NO_REQUEST
, MTM.TIPE
, PPF1.FULL_NAME PEMBUAT
, PPF.FULL_NAME KARYAWAN
--, PJ.NAME DEPT_LAMA
--, PP.NAME POSISI_LAMA
--, HL.LOCATION_CODE LOKASI_LAMA
, MTM.GAJI_LAMA
--, PJ1.NAME DEPT_BARU
--, PP1.NAME POSISI_BARU
--, HL1.LOCATION_CODE LOKASI_BARU
, MTM.GAJI_BARU
, MTM.KETERANGAN
, MTM.ALASAN
, TO_CHAR(MTM.TGL_EFFECTIVE, 'YYYY-MM-DD')
--, PVG.NAME GRADE_LAMA
--, PVG1.NAME GRADE
, PPF3.FIRST_NAME || ' ' || PPF3.LAST_NAME MGR_LAMA
, PPF4.FIRST_NAME || ' ' || PPF4.LAST_NAME MGR_BARU
, MTM.STATUS_KARYAWAN
, MTM.SIFAT_PERUBAHAN
, MTM.JUMLAH_BULAN
--, PVG1.POSITION_ID
--, PP1.POSITION_ID
FROM MJ.MJ_T_MUTASI MTM
INNER JOIN APPS.PER_PEOPLE_F PPF ON PPF.PERSON_ID = MTM.KARYAWAN_ID AND PPF.EFFECTIVE_END_DATE > SYSDATE
INNER JOIN APPS.PER_PEOPLE_F PPF1 ON PPF1.PERSON_ID = MTM.CREATED_BY AND PPF1.EFFECTIVE_END_DATE > SYSDATE
LEFT JOIN APPS.PER_PEOPLE_F PPF3 ON PPF3.PERSON_ID = MTM.MGR_LAMA AND PPF3.EFFECTIVE_END_DATE > SYSDATE
LEFT JOIN APPS.PER_PEOPLE_F PPF4 ON PPF4.PERSON_ID = MTM.MGR_BARU AND PPF4.EFFECTIVE_END_DATE > SYSDATE
LEFT JOIN APPS.PER_JOBS PJ ON PJ.JOB_ID = MTM.DEPT_LAMA_ID
LEFT JOIN APPS.PER_POSITIONS PP ON PP.POSITION_ID = MTM.POSISI_LAMA_ID
LEFT JOIN APPS.PER_VALID_GRADES_V PVG ON PVG.POSITION_ID=PP.POSITION_ID
LEFT JOIN APPS.HR_LOCATIONS HL ON HL.LOCATION_ID = MTM.LOKASI_LAMA_ID 
LEFT JOIN APPS.PER_JOBS PJ1 ON PJ1.JOB_ID = MTM.DEPT_BARU_ID
LEFT JOIN APPS.PER_POSITIONS PP1 ON PP1.POSITION_ID = MTM.POSISI_BARU_ID
LEFT JOIN APPS.HR_LOCATIONS HL1 ON HL1.LOCATION_ID = MTM.LOKASI_BARU_ID
WHERE 1=1
AND MTM.STATUS_DOK NOT IN ('Approved','Disapproved') AND MTM.TINGKAT IN (0, 1)


INNER JOIN APPS.PER_VALID_GRADES_V PVG1 ON PVG1.POSITION_ID=PP1.POSITION_ID


SELECT  *
FROM    APPS.PER_VALID_GRADES_V



SELECT  ID || '|' || NO_REQUEST || '|' || TIPE 
FROM    MJ.MJ_T_MUTASI 
WHERE   ID = 45



SELECT  REPLACE( '00040/SM1/HRD/BRT/09/2018', '/', '_' ) DATA
FROM    DUAL





