<?PHP
include '../../main/koneksi.php';

	$status = "";
	$result = oci_parse($con, "SELECT MNR.ID AS HD_ID
	, MNR.LOCATION_GROUP AS DATA_LOCATION
	, MNR.NOMINAL AS DATA_NOMINAL
	, TO_CHAR(MNR.EFFECTIVE_START_DATE, 'YYYY-MM-DD') AS DATA_START_DATE 
	, TO_CHAR(MNR.EFFECTIVE_END_DATE, 'YYYY-MM-DD') AS DATA_END_DATE 
	, NVL(UPD.FULL_NAME, CRE.FULL_NAME) DATA_UPDATE_BY
	, NVL(TO_CHAR(MNR.LAST_UPDATED_DATE, 'DD-MON-YYYY HH24:MI'), TO_CHAR(MNR.CREATED_DATE, 'DD-MON-YYYY HH24:MI')) DATA_UPDATE_DATE
	, CASE WHEN TO_CHAR(SYSDATE, 'YYYYMMDD') >= TO_CHAR(MNR.EFFECTIVE_START_DATE, 'YYYYMMDD') 
	AND TO_CHAR(SYSDATE, 'YYYYMMDD') <= TO_CHAR(NVL(MNR.EFFECTIVE_END_DATE, TO_DATE('47121231', 'YYYYMMDD')), 'YYYYMMDD') THEN
		'ACTIVE' ELSE 'INACTIVE' END STATUS
	FROM MJ.MJ_M_NOMINAL_RITASI MNR
	LEFT JOIN
	(
		SELECT MMU.ID, PPF.FULL_NAME
		FROM MJ.MJ_M_USER MMU
		INNER JOIN APPS.PER_PEOPLE_F PPF ON PPF.PERSON_ID = MMU.EMP_ID AND PPF.EFFECTIVE_END_DATE > SYSDATE AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y'
	) UPD ON UPD.ID = MNR.LAST_UPDATED_BY
	LEFT JOIN
	(
		SELECT MMU.ID, PPF.FULL_NAME
		FROM MJ.MJ_M_USER MMU
		INNER JOIN APPS.PER_PEOPLE_F PPF ON PPF.PERSON_ID = MMU.EMP_ID AND PPF.EFFECTIVE_END_DATE > SYSDATE AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y'
	) CRE ON CRE.ID = MNR.CREATED_BY
	WHERE 1=1");
	oci_execute($result);
	while($row = oci_fetch_row($result))
	{
		$record = array();
		$record['HD_ID']=$row[0];
		$record['DATA_LOCATION']=$row[1];
		$record['DATA_NOMINAL']=$row[2];
		$record['DATA_START_DATE']=$row[3];
		$record['DATA_END_DATE']=$row[4];
		$record['DATA_UPDATE_BY']=$row[5];
		$record['DATA_UPDATE_DATE']=$row[6];
		$record['DATA_STATUS']=$row[7];
		$data[]=$record;
	}
	
echo json_encode($data); 
?>