<?PHP
include '../../main/koneksi.php';

$where = '';
if (isset($_GET['status'])){		
	if($_GET['status'] != 'ALL'){
		$where = " AND CASE WHEN TO_CHAR(SYSDATE, 'YYYYMMDD') >= TO_CHAR(GP.EFFECTIVE_START_DATE, 'YYYYMMDD') 
		AND TO_CHAR(SYSDATE, 'YYYYMMDD') <= TO_CHAR(NVL(GP.EFFECTIVE_END_DATE, TO_DATE('47121231', 'YYYYMMDD')), 'YYYYMMDD') THEN
        'ACTIVE' ELSE 'INACTIVE' END = '".$_GET['status']."'";
	}
}

	$status = "";
	$result = oci_parse($con, "SELECT GP.ID AS HD_ID
    , GP.LOCATION_GROUP_ID AS DATA_LOCATION_ID
    , MNR.LOCATION_GROUP AS DATA_LOCATION
    , GP.PLANT_ID AS DATA_PLANT_ID
    , HOU.NAME AS DATA_PLANT
    , TO_CHAR(GP.EFFECTIVE_START_DATE, 'YYYY-MM-DD') AS DATA_START_DATE 
    , TO_CHAR(GP.EFFECTIVE_END_DATE, 'YYYY-MM-DD') AS DATA_END_DATE 
    , NVL(UPD.FULL_NAME, CRE.FULL_NAME) DATA_UPDATE_BY
    , NVL(TO_CHAR(GP.LAST_UPDATED_DATE, 'DD-MON-YYYY HH24:MI'), TO_CHAR(GP.CREATED_DATE, 'DD-MON-YYYY HH24:MI')) DATA_UPDATE_DATE
    , CASE WHEN TO_CHAR(SYSDATE, 'YYYYMMDD') >= TO_CHAR(GP.EFFECTIVE_START_DATE, 'YYYYMMDD') 
    AND TO_CHAR(SYSDATE, 'YYYYMMDD') <= TO_CHAR(NVL(GP.EFFECTIVE_END_DATE, TO_DATE('47121231', 'YYYYMMDD')), 'YYYYMMDD') THEN
        'ACTIVE' ELSE 'INACTIVE' END STATUS
    FROM MJ.MJ_M_GROUP_PLANT GP
	INNER JOIN MJ.MJ_M_NOMINAL_RITASI MNR ON MNR.ID = GP.LOCATION_GROUP_ID
	INNER JOIN APPS.HR_ORGANIZATION_UNITS HOU ON HOU.ORGANIZATION_ID = GP.PLANT_ID
    LEFT JOIN
    (
        SELECT MMU.ID, PPF.FULL_NAME
        FROM MJ.MJ_M_USER MMU
        INNER JOIN APPS.PER_PEOPLE_F PPF ON PPF.PERSON_ID = MMU.EMP_ID AND PPF.EFFECTIVE_END_DATE > SYSDATE AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y'
    ) UPD ON UPD.ID = GP.LAST_UPDATED_BY
    LEFT JOIN
    (
        SELECT MMU.ID, PPF.FULL_NAME
        FROM MJ.MJ_M_USER MMU
        INNER JOIN APPS.PER_PEOPLE_F PPF ON PPF.PERSON_ID = MMU.EMP_ID AND PPF.EFFECTIVE_END_DATE > SYSDATE AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y'
    ) CRE ON CRE.ID = GP.CREATED_BY
    WHERE 1=1 ".$where.
	" ORDER BY STATUS DESC");
	oci_execute($result);
	while($row = oci_fetch_row($result))
	{
		$record = array();
		$record['HD_ID']=$row[0];
		$record['DATA_LOCATION_ID']=$row[1];
		$record['DATA_LOCATION']=$row[2];
		$record['DATA_PLANT_ID']=$row[3];
		$record['DATA_PLANT']=$row[4];
		$record['DATA_START_DATE']=$row[5];
		$record['DATA_END_DATE']=$row[6];
		$record['DATA_UPDATE_BY']=$row[7];
		$record['DATA_UPDATE_DATE']=$row[8];
		$record['DATA_STATUS']=$row[9];
		$data[]=$record;
	}
	
echo json_encode($data); 
?>